FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install -yq build-essential python-setuptools python-dev libldap2-dev libsasl2-dev libssl-dev libxslt1-dev libffi-dev libpq-dev
RUN apt-get install -yq tmux git vim python-virtualenv postgresql inetutils-ping telnet memcached npm ldap-utils
